### ISSUE TITLE
AttributeError: 'DatasetDict' object has no attribute 'shard' when running SimHash deduplication

### ISSUE THREAD

**Issue by Dodero10** [ChenghaoMou/text-dedup#93]
When I run 
!python -m text_dedup.simhash \
  --path "/content/A" \
  --output "/content/deduplicated.csv" \
  --column "question" \
  --batch_size 10000 \
  --use_auth_token false
  
I have a issue. Can you help me to solve this?

Generating train split: 382951 examples [00:39, 9804.19 examples/s] 
Map (num_proc=2): 100% 382951/382951 [00:40<00:00, 9521.03 examples/s] 
SimHashing... (num_proc=2): 100% 382951/382951 [04:45<00:00, 1343.27 examples/s]
Iterating SimHashes...:   0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/simhash.py", line 466, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/utils/args.py", line 61, in wrapper
    return func(*args, **kwargs, io_args=io_args)
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/utils/args.py", line 85, in wrapper
    return func(*args, **kwargs, meta_args=meta_args)
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/utils/args.py", line 183, in wrapper
    return func(*args, **kwargs, simhash_args=simhash_args)
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/simhash.py", line 371, in main
    with timer("Total"):
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/utils/timer.py", line 18, in __exit__
    raise exc_val
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/simhash.py", line 395, in main
    with timer("Clustering"):
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/utils/timer.py", line 18, in __exit__
    raise exc_val
  File "/usr/local/lib/python3.10/dist-packages/text_dedup/simhash.py", line 402, in main
    embedded_shard = embedded.shard(
AttributeError: 'DatasetDict' object has no attribute 'shard'. Did you mean: 'shape'?

**Comment by ChenghaoMou** [comment]
It seems that the path is pointing to a DatasetDict instead of Dataset. You can modify the [loading code](https://github.com/ChenghaoMou/text-dedup/blob/85dd9272e2cc0e873b1abb556807e1596f722284/text_dedup/utils/load.py#L28) to use a specific split.

**Comment by Dodero10** [comment]
Thank you very much. I fixed it!
